### ISSUE TITLE
Where goes HolyGhost.js

### ISSUE THREAD

**Issue by leberkas** [m-kraus/HolyGhost#1]
Hello, great work!
But i don't know what to do with HolyGhost.js. Do i need it? Where do i need it?

Thanks!

**Comment by m-kraus** [comment]
Sorry for the bad documentation at the moment...
I am on holidays at present, but in short you should create a directory, e.g. /opt/holyghost/ and put HolyGhost (which is a perl file) and HolyGhost.js into that newly created directory. Make sure phantomjs and casperjs are in your search path and executable of course. Then you should be able to run a test case.
Hope that helps.

**Comment by leberkas** [comment]
Thanks, i can see clearly now :)
